name: Android CI (APK & AAB)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  FPT_API_KEY: ${{ secrets.FPT_API_KEY }}
  ANDROID_KEYSTORE_PATH: android/keystore.jks

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses

      - name: Flutter pub get
        run: flutter pub get

      # Build debug APK (đủ test nội bộ)
      - name: Build debug APK
        run: flutter build apk --debug --dart-define=FPT_API_KEY=$FPT_API_KEY

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      # (GIAI ĐOẠN 2: ký release) — để trống bây giờ cho gọn
      # - name: Decode keystore from secret (optional)
      #   if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
      #   run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > $ANDROID_KEYSTORE_PATH
      # - name: Write keystore.properties (optional)
      #   if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
      #   run: |
      #     cat > android/keystore.properties << 'EOF'
      #     storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      #     keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
      #     keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
      #     storeFile=${{ env.ANDROID_KEYSTORE_PATH }}
      #     EOF
      # - name: Build release APK
      #   run: flutter build apk --release --dart-define=FPT_API_KEY=$FPT_API_KEY
      # - name: Upload release APK
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: app-release-apk
      #     path: build/app/outputs/flutter-apk/app-release.apk
      # - name: Build AAB
      #   run: flutter build appbundle --release --dart-define=FPT_API_KEY=$FPT_API_KEY
      # - name: Upload AAB
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: app-release-aab
      #     path: build/app/outputs/bundle/release/app-release.aab
